"""lappy.symmetry -- symmetry-reduced Method of Particular Solutions.

Most benchmark domains (and most domains that show up in shape optimization)
have a nontrivial isometry group G. The Dirichlet spectrum then splits into
irreducible sectors, and MPS can be run one sector at a time. Three things
improve at once:

1. **Conditioning / resolution.** Each sector needs roughly ``|G|`` times
   fewer independent basis functions to reach the same resolution, so at a
   fixed cost the per-sector basis is far richer than the full-domain basis.

2. **Degeneracy separation.** Eigenvalues that are degenerate (or nearly so)
   in the full problem land in *different* sectors, where each is a simple,
   well-isolated minimum of its own tension curve. This is the single
   biggest accuracy win for domains like ``reg_ngon(8)``, whose full-domain
   tension curve has three eigenvalues inside a window of width 4e-3.

3. **Cost.** The GSVD is cubic in the basis size. Halving the column count
   is an 8x saving per sector, 4x overall for a two-element group.

Implementation note: rather than construct a reduced *geometry* with mixed
Dirichlet/Neumann conditions on the symmetry axes (fiddly, and it changes
the corner structure the basis builder sees), we symmetrize the *basis*:

    phi_j^chi(z) = sum_{g in G} chi(g) phi_j(g z)

Every ``phi_j^chi`` still solves the Helmholtz equation (the ``g`` are
isometries), and it lies in the ``chi``-isotypic subspace by construction.
Collocating it on the part of ``dOmega`` inside a fundamental domain is then
equivalent to the full problem restricted to that sector -- the symmetry
axes need no equations at all, since the projected functions satisfy the
right condition there identically.

The symmetrized family is rank-deficient by a factor ``|G|`` (phi_j and
phi_{g j} project to the same function up to sign). ``MPSEigensolver``'s
existing SVD regularization discards the dependent directions, so no
explicit column pruning is required for correctness; ``prune_columns``
does it anyway to recover the cubic cost saving.

Only real characters are supported, i.e. groups that are elementary abelian
2-groups (generated by commuting involutions: reflections and half-turns).
That covers every symmetric domain in the benchmark set.
"""
import numpy as np

from .bases import ParticularBasis
from .geometry import PointSet


# ---------------------------------------------------------------------------
# planar isometries
# ---------------------------------------------------------------------------

class Isometry:
    """A planar isometry ``z -> a*z + b`` (direct) or ``z -> a*conj(z) + b``
    (opposite), stored in complex form with ``|a| == 1``.

    ``half`` is a signed linear functional that is negated by the isometry
    (``half(g z) == -half(z)``); the closed half-plane ``half >= 0`` is a
    fundamental domain for the two-element group ``{e, g}``. It is ``None``
    for the identity.
    """

    def __init__(self, a, b, conj, name='g', half=None):
        self.a, self.b, self.conj, self.name = complex(a), complex(b), bool(conj), name
        self.half = half

    def __call__(self, z):
        z = np.asarray(z)
        return self.a * (np.conj(z) if self.conj else z) + self.b

    def grad_pullback(self, G):
        """Map an evaluated gradient ``G = f_x + i f_y`` at ``g(z)`` to the
        gradient of ``f o g`` at ``z``.

        Direct (``M = R_theta``): ``M^T = R_{-theta}``, i.e. multiply by
        ``conj(a)``. Opposite (``M = R_theta C``, ``C`` = conjugation):
        ``M^T = C R_{-theta}``, i.e. multiply by ``conj(a)`` then conjugate,
        which is ``a * conj(G)``.
        """
        return self.a * np.conj(G) if self.conj else np.conj(self.a) * G

    def __repr__(self):
        return f'Isometry({self.name})'


def identity():
    return Isometry(1.0, 0.0, False, name='e')


def reflection(p0, direction):
    """Reflection across the line through ``p0`` with complex ``direction``.

    ``z -> p0 + d^2 * conj(z - p0)`` where ``d = direction/|direction|``.
    """
    p0 = complex(p0)
    d = complex(direction)
    d /= abs(d)
    a = d * d
    b = p0 - a * np.conj(p0)

    def half(z):
        # signed distance to the line, positive on the left of `direction`
        return np.imag(np.conj(d) * (np.asarray(z) - p0))

    return Isometry(a, b, True, name=f'refl({p0:g},{d:g})', half=half)


def half_turn(center, direction=1.0):
    """Rotation by pi about ``center`` (``z -> 2c - z``).

    A fundamental domain is any half-plane whose boundary line passes
    through the center; ``direction`` selects which one (the cut line runs
    along ``direction``).
    """
    c = complex(center)
    d = complex(direction)
    d /= abs(d)

    def half(z):
        return np.imag(np.conj(d) * (np.asarray(z) - c))

    return Isometry(-1.0, 2 * c, False, name=f'rot180({c:g})', half=half)


# ---------------------------------------------------------------------------
# groups and sectors
# ---------------------------------------------------------------------------

class SymmetryGroup:
    """An elementary abelian 2-group of planar isometries, given by commuting
    involutive generators.

    ``sectors()`` enumerates the real characters as sign tuples; ``elements``
    holds ``(isometry, sign_exponents)`` for every group element, expanded as
    products over subsets of the generators.
    """

    def __init__(self, generators, name=''):
        self.generators = list(generators)
        self.name = name
        self._expand()

    def _expand(self):
        k = len(self.generators)
        elems = []
        for mask in range(2 ** k):
            g = identity()
            expo = []
            for i in range(k):
                bit = (mask >> i) & 1
                expo.append(bit)
                if bit:
                    g = _compose(self.generators[i], g)
            elems.append((g, tuple(expo)))
        self.elements = elems

    @property
    def order(self):
        return len(self.elements)

    def sectors(self):
        """All real characters, as tuples of +-1 (one entry per generator)."""
        k = len(self.generators)
        return [tuple(1 - 2 * ((m >> i) & 1) for i in range(k)) for m in range(2 ** k)]

    def character(self, sector, expo):
        chi = 1
        for s, e in zip(sector, expo):
            if e:
                chi *= s
        return chi

    def in_fundamental_domain(self, z, tol=0.0):
        """Boolean mask: points strictly inside the fundamental domain
        (intersection of the generators' positive half-planes)."""
        z = np.asarray(z)
        mask = np.ones(z.shape, dtype=bool)
        for g in self.generators:
            mask &= g.half(z) > tol
        return mask

    def __repr__(self):
        return f'SymmetryGroup({self.name or len(self.generators)} generators, order {self.order})'


def _compose(g1, g2):
    """``g1 o g2``, where ``g(z) = a * z^(c) + b`` and ``z^(c)`` means
    ``conj(z)`` when ``c`` is set."""
    a2, b2, c2 = g2.a, g2.b, g2.conj
    a1, b1, c1 = g1.a, g1.b, g1.conj
    if c1:
        a = a1 * np.conj(a2)
        b = a1 * np.conj(b2) + b1
    else:
        a = a1 * a2
        b = a1 * b2 + b1
    conj = c1 ^ c2
    return Isometry(a, b, conj, name=f'{g1.name}o{g2.name}')


# ---------------------------------------------------------------------------
# symmetrized basis
# ---------------------------------------------------------------------------

class SymmetrizedBasis(ParticularBasis):
    """Projection of ``basis`` onto the ``sector`` isotypic subspace of ``group``.

    ``phi_j^chi(z) = sum_{g} chi(g) phi_j(g z)``. Column count is unchanged
    (rank is not: see module docstring), unless ``cols_keep`` selects a
    subset -- see ``prune_columns``.
    """

    def __init__(self, basis, group, sector, cols_keep=None):
        self.basis = basis
        self.group = group
        self.sector = tuple(sector)
        self.cols_keep = None if cols_keep is None else np.asarray(cols_keep, dtype=int)
        self._chis = [group.character(self.sector, expo) for _, expo in group.elements]
        self._maps = [g for g, _ in group.elements]

    def __len__(self):
        return len(self.basis) if self.cols_keep is None else len(self.cols_keep)

    def __str__(self):
        return f'SymmetrizedBasis({self.basis}, sector={self.sector})'

    def _resolve(self, cols):
        """Map local column indices to the wrapped basis's indices."""
        if self.cols_keep is None:
            return cols
        return self.cols_keep if cols is None else self.cols_keep[np.asarray(cols)]

    def _eval_pointset(self, lam, pts, cols=None):
        inner = self._resolve(cols)
        z = pts.pts if isinstance(pts, PointSet) else np.asarray(pts)
        out = None
        for g, chi in zip(self._maps, self._chis):
            A = self.basis(lam, PointSet(g(z)), cols=inner)
            out = chi * A if out is None else out + chi * A
        return out

    def _grad_pointset(self, lam, pts, cols=None):
        inner = self._resolve(cols)
        z = pts.pts if isinstance(pts, PointSet) else np.asarray(pts)
        out = None
        for g, chi in zip(self._maps, self._chis):
            G = g.grad_pullback(self.basis.grad(lam, PointSet(g(z)), cols=inner))
            out = chi * G if out is None else out + chi * G
        return out

    def corner_terms(self, domain=None):
        cid, expo = self.basis.corner_terms(domain)
        # A projected column is singular at the whole orbit of its corner, so
        # the single-corner labelling no longer applies; report "regular".
        n = len(self)
        return np.full(n, -1, dtype=int), np.zeros(n)


def prune_columns(sym_basis, lam, pts, kill_tol=1e-8, dup_tol=1e-14):
    """Drop the columns the projection makes redundant, returning a new
    ``SymmetrizedBasis``.

    The projection is redundant in two distinct ways, which need two
    distinct tests:

    1. **Annihilated columns.** A basis function centred on a point *fixed*
       by some group element (e.g. Fourier--Bessel terms at a corner sitting
       on a mirror line) is already even or odd about that element, so
       roughly half of them are mapped to zero. Detected by comparing the
       projected column norm to the *unprojected* one -- an absolute test
       would be meaningless, since legitimate high-order Bessel columns are
       themselves as small as 1e-150 and must be kept (they are computed to
       full *relative* accuracy and do carry real approximation power).

    2. **Orbit duplicates.** For a basis function at a point *moved* by the
       group, ``phi_c`` and ``phi_{g c}`` project to the same function up to
       sign. Neither is annihilated; they are exact duplicates, caught by a
       pivoted QR on the projection-normalized columns.

    ``dup_tol`` is deliberately as tight as the solver's own ``rtol``: the
    aim is to remove structural redundancy only, and leave every genuine
    (if near-dependent) direction for the solver's regularization to weigh
    at each ``lam``. Getting this wrong in the aggressive direction silently
    costs several digits.
    """
    import scipy.linalg as sla

    ps = PointSet(np.asarray(pts))
    inner = sym_basis.cols_keep
    A = sym_basis(lam, ps)
    A_raw = sym_basis.basis(lam, ps, cols=inner)

    proj_nrm = np.linalg.norm(A, axis=0)
    raw_nrm = np.linalg.norm(A_raw, axis=0)
    raw_nrm[raw_nrm == 0] = 1.0
    alive = np.nonzero(proj_nrm > kill_tol * raw_nrm)[0]
    if alive.size == 0:
        return SymmetrizedBasis(sym_basis.basis, sym_basis.group,
                                sym_basis.sector, cols_keep=np.array([], dtype=int))

    B = A[:, alive] / proj_nrm[alive]
    _, R, piv = sla.qr(B, mode='economic', pivoting=True)
    diag = np.abs(np.diag(R))
    rank = int(np.sum(diag > dup_tol * diag[0]))
    keep = np.sort(alive[piv[:rank]])
    inner = keep if sym_basis.cols_keep is None else sym_basis.cols_keep[keep]
    return SymmetrizedBasis(sym_basis.basis, sym_basis.group, sym_basis.sector,
                            cols_keep=inner)


# ---------------------------------------------------------------------------
# fundamental-domain point sets
# ---------------------------------------------------------------------------

def fundamental_bdry_pts(domain, group, n_per_seg, tol=1e-10, **kwargs):
    """Boundary collocation points lying strictly inside ``group``'s
    fundamental domain.

    Points on a symmetry axis are dropped: the projected basis satisfies the
    induced Dirichlet/Neumann condition there identically, so they carry no
    information (and for odd sectors would give identically-zero rows).
    """
    pts = domain.bdry_pts(n_per_seg, **kwargs)
    z = pts.pts if isinstance(pts, PointSet) else np.asarray(pts)
    keep = group.in_fundamental_domain(z, tol=tol)
    return PointSet(z[keep])


def fundamental_int_pts(domain, group, npts, oversamp=None, tol=1e-8, rng=None,
                        max_tries=8):
    """``npts`` random interior points inside ``group``'s fundamental domain.

    Draws from the full domain and rejects, topping up until the target count
    is reached (the acceptance rate is ~1/|G| but the fundamental domain is
    not in general an equal-area slice of the bounding box the sampler uses).
    """
    if oversamp is None:
        oversamp = 2 * group.order
    got = []
    have = 0
    for _ in range(max_tries):
        # `rng` was in this signature from the start but was never used, so
        # sector solves drew from the global RNG regardless of what the caller
        # asked for. Forward it.
        draw = domain.int_pts(method='random', npts_rand=int(npts * oversamp) + 16,
                              rng=rng)
        z = draw.pts if isinstance(draw, PointSet) else np.asarray(draw)
        z = z[group.in_fundamental_domain(z, tol=tol)]
        got.append(z)
        have += len(z)
        if have >= npts:
            break
        oversamp *= 2
    z = np.concatenate(got)
    if len(z) > npts:
        z = z[:npts]
    return PointSet(z)


# ---------------------------------------------------------------------------
# symmetry registry for the benchmark domains
# ---------------------------------------------------------------------------

def domain_symmetry(name, **params):
    """Symmetry group for a named benchmark domain, or ``None``.

    Verified against the vertex lists in ``lappy.geometry``; see
    ``tests/test_symmetry.py`` for the machine check that each generator
    really maps the boundary to itself.
    """
    v = reflection  # local alias

    if name == 'chevron':
        # vertices [-1, i*h1, 1, i*h2]: mirror in the imaginary axis
        return SymmetryGroup([v(0, 1j)], name='chevron mirror')

    if name == 'iso_tri':
        # vertices [1, i*h, -1]
        return SymmetryGroup([v(0, 1j)], name='iso_tri mirror')

    if name == 'mushroom':
        return SymmetryGroup([v(0, 1j)], name='mushroom mirror')

    if name == 'L_shape':
        # vertices [0, i, -1+i, -1-i, 1-i, 1]: mirror in the line y = x
        return SymmetryGroup([v(0, 1 + 1j)], name='L_shape diagonal')

    if name == 'cut_square':
        # unit square with the (1,1) corner cut: mirror in y = x
        return SymmetryGroup([v(0, 1 + 1j)], name='cut_square diagonal')

    if name == 'H_shape':
        # 180-degree rotation about (0.5, -0.5); no reflection symmetry
        return SymmetryGroup([half_turn(0.5 - 0.5j, direction=1 + 1j)],
                             name='H_shape half-turn')

    if name == 'ellipse':
        return SymmetryGroup([v(0, 1), v(0, 1j)], name='ellipse D2')

    if name == 'stadium':
        L = params.get('L', 1.0)
        return SymmetryGroup([v(L / 2, 1), v(L / 2, 1j)], name='stadium D2')

    if name == 'reg_ngon':
        n = params['n']
        # vertices exp(2 pi i k / n): the x-axis is always a mirror; for even
        # n the y-axis is too, giving a Klein four-group (the largest
        # elementary abelian 2-subgroup of D_n realisable with real
        # characters). Odd n admits only the single mirror.
        if n % 2 == 0:
            return SymmetryGroup([v(0, 1), v(0, 1j)], name=f'reg_ngon({n}) D2')
        return SymmetryGroup([v(0, 1)], name=f'reg_ngon({n}) mirror')

    if name == 'rect':
        # rect(L, H) has vertices [0, L, L+iH, iH]: mirrors in both mid-lines.
        # The square's full symmetry is D4, but only the D2 subgroup has real
        # characters, which is what SymmetryGroup supports.
        L, H = params.get('L', 1.0), params.get('H', 1.0)
        return SymmetryGroup([v(L / 2 + 1j * H / 2, 1),
                              v(L / 2 + 1j * H / 2, 1j)], name='rect D2')

    if name == 'eq_tri':
        # vertices [0, l, l/2 + i*l*sqrt(3)/2]: D3 has only one real character
        # pair, so take the single mirror through the apex.
        l = params.get('l', 1.0)
        return SymmetryGroup([v(l / 2, 1j)], name='eq_tri mirror')

    if name == 'iso_right_tri':
        # vertices [0, l, i*l]: mirror in y = x
        return SymmetryGroup([v(0, 1 + 1j)], name='iso_right_tri diagonal')

    if name == 'disk':
        # O(2); any two orthogonal mirrors give a usable Klein four-group.
        return SymmetryGroup([v(0, 1), v(0, 1j)], name='disk D2')

    if name == 'disk_sector':
        # disk_sector(r, theta) spans arg z in [0, theta]: the bisector is a
        # mirror. Only that one -- the two straight edges are not parallel, so
        # there is no second independent reflection.
        theta = params.get('theta', np.pi / 2)
        return SymmetryGroup([v(0, np.exp(1j * theta / 2))],
                             name='disk_sector bisector')

    if name == 'parallelogram':
        # vertices [0, b, b + h/tan(a) + ih, h/tan(a) + ih]: point symmetry
        # about the centroid only; a generic parallelogram has no mirror.
        b = params.get('b', 1.0)
        h = params.get('h', 1.0)
        alpha = params.get('alpha', np.pi / 3)
        c = (b + h / np.tan(alpha) + 1j * h) / 2
        return SymmetryGroup([half_turn(c, direction=1.0)],
                             name='parallelogram half-turn')

    if name in ('GWW1', 'GWW2'):
        return None  # genuinely asymmetric

    return None
